#!/bin/sh

# Kill Pipewire if already runnding 
pkill pipewire
pkill pipewire-pulse

# Start pipewire
pipewire &
pipewire-pulse &

#LAUNCHERS
$HOME/.config/bspwm/autostart.sh
#fix for moving spotify to specific workspace
#bspc config external_rules_command ~/.config/bspwm/scripts/external_rules_command

bspc rule -r "*"

#BSPWM configuration
#bspc config border_radius       8
bspc config border_width         3
bspc config window_gap           10
bspc config top_padding          30
bspc config bottom_padding       10
bspc config left_padding         10
bspc config right_padding        10
bspc config single_monocle       false
#bspc config click_to_focus       true
bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      true
#bspc config focus_by_distance    true
bspc config focus_follows_pointer true
#bspc config history_aware_focus  true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#BSPWM coloring
bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color    "#f93219" 
#bspc config focused_border_color	"#5e81ac"
bspc config presel_feedback_color	"#5e81ac"
#bspc config urgent_border_color 	"#dd2727"


# Get the connected monitor
connected=$(xrandr --query | grep " connected" | cut -d" " -f1 | wc -l)

# Set bspwm rules based on the number of connected monitors
if [ $connected -eq 1 ]; then
    # Single monitor rule
    bspc monitor -d 1 2 3 4 5 6
else
    # Dual monitor rule
    bspc monitor eDP1 -d 1 2 3 4 5
    bspc monitor HDMI1 -d 6 7 8 9 10
fi
#Single monitor
#bspc monitor HDMI1 -d 1 2 3 4 5 6 7 8 9 10

#Dual monitor
#find out names with arandr or xrandr
#bspc monitor DP-2 -d 1 2 3 4 5 6 7 8 9
#bspc monitor LVDS1 -d 1 2 3 4
#bspc monitor DP3 -d  5 6 7 8 9
#bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor eDP1 -d 1 2 3 4 5
#bspc monitor HDMI1 -d 6 7 8 9 10
#bspc monitor HDMI1 -d 1 2 3 4 5
#bspc monitor HDMI2 -d 6 7 8 9 10

#Fullscreen applications
bspc rule -a inkscape state=fullscreen
bspc rule -a Vlc state=fullscreen
bspc rule -a VirtualBox Manager state=fullscreen
bspc rule -a 'Emacs' state=fullscreen
bspc rule -a 'tmaster.exe' state=fullscreen
bspc rule -a VirtualBox Machine state=fullscreen
#bspc rule -a Gimp state=fullscreen

#Floating applications
bspc rule -a Arandr state=floating
bspc rule -a Arcolinux-tweak-tool.py state=floating
bspc rule -a Arcolinux-welcome-app.py state=floating
bspc rule -a Arcolinux-calamares-tool.py state=floating
bspc rule -a feh state=floating
bspc rule -a 'Tor Browser:Navigator' state=pseudo_tiled private=on
bspc rule -a 'Nitrogen' state=floating
bspc rule -a 'Pamac-manager' state=floating
bspc rule -a 'spotify' state=floating
bspc rule -a 'Anydesk' state=floating
bspc rule -a 'Nm-connection-editor' state=floating
bspc rule -a 'lxappearance' state=floating
bspc rule -a 'xdman-Main' state=floating
bspc rule -a 'LibreWolf' state=floating
bspc rule -a 'stacer' state=floating
bspc rule -a 'Bitwarden' state=floating
bspc rule -a 'packettracer' state=floating private=on
bspc rule -a 'Fr.handbrake.ghb' state=floating
bspc rule -a 'VirtualBox Manager' state=floating
#bspc rule -a mpv desktop='^2'  follow=on
bspc rule -a simplesceenrecorderi desktop='^9' state=floating 
bspc rule -a Brave-browser state=floating
bspc rule -a obs desktop='9' state=floating
bspc rule -a easyeffects desktop='^10' state=floating follow=on
bspc rule -a qBittorrent state=floating
bspc rule -a mpv desktop='^2'state=floating follow=on
bspc rule -a winscp.exe state=floating

#bspc rule -a mpv state=floating sticky=on
#bspc rule -a Font-manager state=floating
bspc rule -a Galculator state=floating
bspc rule -a SimpleScreenRecorder state=floating
#bspc rule -a Gpick state=floating sticky=on
#bspc rule -a Nitrogen state=floating
bspc rule -a Oblogout state=floating
#bspc rule -a Pavucontrol state=floating sticky=on
#bspc rule -a Peek state=floating
#bspc rule -a rofi state=floating sticky=on
#bspc rule -a Skype state=floating
bspc rule -a Stacer state=floating
#bspc rule -a Xfce4-appfinder state=floating sticky=on
bspc rule -a Xfce4-terminal state=floating
bspc rule -a "Virt-manager" state=floating
bspc rule -a Gnome-disks state=floating

#Tiled applications
bspc rule -a Xfce4-settings-manager state=tiled
bspc rule -a Zathura state=tiled

#open applications on specific workspaces
bspc rule -a Firefox desktop='^2' follow=on
#bspc rule -a Google-chrome desktop='^1' follow=on
#bspc rule -a Chromium desktop='^1'  follow=on
#bspc rule -a Subl desktop='^2' follow=on
#bspc rule -a Atom desktop='^2' follow=on
#bspc rule -a Steam desktop='^5'
#bspc rule -a vlc desktop='^6'  follow=on
#bspc rule -a Vivaldi-stable desktop='^6' follow=on
#bspc rule -a Vivaldi-snapshot desktop='^6' follow=on
#bspc rule -a Transmission-gtk desktop='^7' follow=on
#bspc rule -a Thunar desktop='^8' follow=on
#bspc rule -a discord desktop='^9' follow=on
#bspc rule -a Spotify desktop='^10' follow=on

#Spotify fix  --move desktop 10
#sleep 1
#wmctrl -r Spotify -t 10
#exit

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DP-1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI2)

###External rules
##Pseudo automatic mode: always splits focused window when opening new window
#bspc config external_rules_command ~/.config/bspwm/scripts/pseudo_automatic_mode
##Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command ~/.config/bspwm/scripts/adjust-new-window
