#!/bin/sh

# Kill Pipewire if already runnding 
pkill pipewire
pkill pipewire-pulse

# Start pipewire
pipewire &
pipewire-pulse &

#LAUNCHERS
$HOME/.config/bspwm/autostart.sh

bspc rule -r "*"

#BSPWM configuration
bspc config border_width         3
bspc config window_gap           10
bspc config top_padding          30
bspc config bottom_padding       10
bspc config left_padding         10
bspc config right_padding        10
bspc config single_monocle       false
bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#BSPWM coloring
bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color    "#f93219" 
bspc config presel_feedback_color	"#5e81ac"

# Get the connected monitor
connected=$(xrandr --query | grep " connected" | cut -d" " -f1 | wc -l)

# Set bspwm rules based on the number of connected monitors
if [ $connected -eq 1 ]; then
    # Single monitor rule
    bspc monitor -d 1 2 3 4 5 6
else
    # Dual monitor rule
    bspc monitor eDP1 -d 1 2 3 4 5
    bspc monitor HDMI1 -d 6 7 8 9 10
fi
#Single monitor
#bspc monitor HDMI1 -d 1 2 3 4 5 6 7 8 9 10

#Dual monitor
#find out names with arandr or xrandr
#bspc monitor DP-2 -d 1 2 3 4 5 6 7 8 9
#bspc monitor LVDS1 -d 1 2 3 4
#bspc monitor DP3 -d  5 6 7 8 9
#bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor eDP1 -d 1 2 3 4 5
#bspc monitor HDMI1 -d 6 7 8 9 10
#bspc monitor HDMI1 -d 1 2 3 4 5
#bspc monitor HDMI2 -d 6 7 8 9 10

#Fullscreen applications
bspc rule -a inkscape state=fullscreen
bspc rule -a Vlc state=fullscreen
bspc rule -a VirtualBox Manager state=fullscreen
bspc rule -a 'Emacs' state=fullscreen
bspc rule -a 'tmaster.exe' state=fullscreen
bspc rule -a VirtualBox Machine state=fullscreen
#Floating applications
bspc rule -a Arandr state=floating
bspc rule -a feh state=floating
bspc rule -a 'Tor Browser:Navigator' state=pseudo_tiled private=on
bspc rule -a 'Nitrogen' state=floating
bspc rule -a 'spotify' state=floating
bspc rule -a 'Nm-connection-editor' state=floating
bspc rule -a 'lxappearance' state=floating
bspc rule -a 'xdman-Main' state=floating
bspc rule -a 'stacer' state=floating
bspc rule -a 'Fr.handbrake.ghb' state=floating
bspc rule -a 'VirtualBox Manager' state=floating
bspc rule -a simplesceenrecorderi desktop='^9' state=floating 
bspc rule -a easyeffects desktop='^10' state=floating follow=on
bspc rule -a qBittorrent state=floating
bspc rule -a mpv desktop='^2'state=floating follow=on
bspc rule -a Galculator state=floating
bspc rule -a SimpleScreenRecorder state=floating
bspc rule -a Oblogout state=floating
bspc rule -a Stacer state=floating
bspc rule -a Xfce4-terminal state=floating
bspc rule -a "Virt-manager" state=floating
bspc rule -a Gnome-disks state=floating
#Tiled applications
bspc rule -a Xfce4-settings-manager state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Firefox desktop='^2' follow=on
